/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import java.awt.Panel;
import javax.swing.JLabel;

/**
 *
 * @author santi
 */
public class VentanaCuotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCuotas
     */
    double prestamo;
    double interes;
    int plazo;

    public VentanaCuotas(double prestamo, double interes, int plazo) {
        initComponents();

        this.prestamo = prestamo;
        this.interes = interes;
        this.plazo = plazo;

    }

    public void mostrar() {
        
        jPanel1.removeAll();
        jPanel1.updateUI();
        double cuota = prestamo / plazo;
        JLabel label;
        double[][] matriz = new double[plazo][5];
        matriz[0][0] = 0;
        matriz[0][1] = 0;
        matriz[0][2] = 0;
        matriz[0][3] = 0;
        matriz[0][4] = prestamo;
        for (int i = 1; i < plazo; i++) {
            for (int j = 0; j < 5; j++) {
                if (j == 0) {
                    matriz[i][j] = i;
                }
                if (j == 1) {
                    matriz[i][j] = cuota;
                }
                if (j == 2) {
                    matriz[i][j] = matriz[i - 1][4] * (interes / 100);
                }
                if (j == 3) {
                    matriz[i][j] = matriz[i][2] + cuota;
                }
                if (j == 4) {
                    matriz[i][j] = matriz[i - 1][4] - cuota;
                }
            }
        }
        String[] c = {"Mes", "Cuota", "Interes", "Amortizacion", "Capital"};
        for (int i = 0; i < 5; i++) {
            label = new JLabel();
            label.setSize(110, 30);
            label.setText(c[i]);
            jPanel1.add(label);
        }
        jPanel1.updateUI();
        for (int i = 0; i < plazo; i++) {
            for (int j = 0; j < 5; j++) {
                label = new JLabel();
                label.setSize(110, 30);
                label.setText(matriz[i][j] + "");
                jPanel1.add(label);
            }

        }
        jPanel1.updateUI();

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(495, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        mostrar();

    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
