/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorCasa;
import ec.ups.edu.controlador.ControladorCredito;
import ec.ups.edu.controlador.ControladorPersona;
import ec.ups.edu.modelo.Casa;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    VentanaIngresoCasas ventanaIngresoCasa;
    VentanaRegistroPersonas ventanaPersona;
    VentanaCredito ventanaCredito;
    VentanaIniciarSesion ventanaIniciarSesion;
    VentanaCuotas ventanaCuotas;

    ControladorCasa controladorCasa;
    ControladorPersona controladorPersona;
    ControladorCredito controladorCredito;
    Casa casa;

    public VentanaPrincipal() {
        initComponents();

        casa = new Casa();

        this.controladorCasa = controladorCasa.getControladorCasa();
        this.controladorPersona = ControladorPersona.getControladorPersona();
        this.controladorCredito = controladorCredito.getControladorCasa();

        ventanaIngresoCasa = new VentanaIngresoCasas();
        ventanaPersona = new VentanaRegistroPersonas();
        ventanaCredito = new VentanaCredito(controladorCredito, controladorPersona, controladorCasa);
        ventanaIniciarSesion = new VentanaIniciarSesion(this);
        ventanaCuotas = new VentanaCuotas(PROPERTIES, WIDTH, WIDTH);
        
        itemCredito.setVisible(false);
        itemGestion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemRegistroPersona = new javax.swing.JMenuItem();
        itemIniciarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        itemGestion = new javax.swing.JMenu();
        itemRegistroCasa = new javax.swing.JMenuItem();
        itemCredito = new javax.swing.JMenuItem();
        itemRegistroCasa1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio ");

        itemRegistroPersona.setMnemonic('o');
        itemRegistroPersona.setText("Registro Persona");
        itemRegistroPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroPersonaActionPerformed(evt);
            }
        });
        fileMenu.add(itemRegistroPersona);

        itemIniciarSesion.setMnemonic('s');
        itemIniciarSesion.setText("Iniciar Sesion");
        itemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(itemIniciarSesion);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        fileMenu.add(itemSalir);

        menuBar.add(fileMenu);

        itemGestion.setMnemonic('e');
        itemGestion.setText("Gestion");

        itemRegistroCasa.setMnemonic('s');
        itemRegistroCasa.setText("Registro Casa");
        itemRegistroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroCasaActionPerformed(evt);
            }
        });
        itemGestion.add(itemRegistroCasa);

        itemCredito.setMnemonic('s');
        itemCredito.setText("Credito");
        itemCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreditoActionPerformed(evt);
            }
        });
        itemGestion.add(itemCredito);

        itemRegistroCasa1.setMnemonic('s');
        itemRegistroCasa1.setText("Ventana cuotas");
        itemRegistroCasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroCasa1ActionPerformed(evt);
            }
        });
        itemGestion.add(itemRegistroCasa1);

        menuBar.add(itemGestion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemRegistroPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroPersonaActionPerformed

        desktopPane.add(ventanaPersona);
        ventanaPersona.setVisible(true);

    }//GEN-LAST:event_itemRegistroPersonaActionPerformed

    private void itemRegistroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroCasaActionPerformed

        desktopPane.add(ventanaIngresoCasa);
        ventanaIngresoCasa.setVisible(true);

    }//GEN-LAST:event_itemRegistroCasaActionPerformed

    private void itemCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreditoActionPerformed

        desktopPane.add(ventanaCredito);
        ventanaCredito.setVisible(true);

    }//GEN-LAST:event_itemCreditoActionPerformed

    private void itemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionActionPerformed

        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);

    }//GEN-LAST:event_itemIniciarSesionActionPerformed

    private void itemRegistroCasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroCasa1ActionPerformed
        
        desktopPane.add(ventanaCuotas);
        ventanaCuotas.setVisible(true);

        
    }//GEN-LAST:event_itemRegistroCasa1ActionPerformed

    public JMenuItem getventanaIngresoCasa() {

        return itemRegistroCasa;

    }

    public JMenuItem getventanaCredito() {

        return itemCredito;

    }

    public JMenu getGestion() {

        return itemGestion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemCredito;
    private javax.swing.JMenu itemGestion;
    private javax.swing.JMenuItem itemIniciarSesion;
    private javax.swing.JMenuItem itemRegistroCasa;
    private javax.swing.JMenuItem itemRegistroCasa1;
    private javax.swing.JMenuItem itemRegistroPersona;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
